openapi: 3.0.0
info:
  version: 1.2.3
  title: AMF handover APIs
  description: |
    AMF Handover service
    © 2023, ETRI
    All rights reserved.
servers:
  - url: '{apiRoot}/amf-handover/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501.

paths:
  /require/{ueId}:
    post:
      operationId: HandoverRequire
      parameters:
        - name: ueId
          in: path
          required: true
          schema:
            type: integer
            format: int64

      requestBody:
        content:
          application/json:
            schema:
              $ref: 'ETRI_Common_Data.yaml#/components/schemas/HandoverRequire'
        required: true
      responses:
        '201':
          description: HandoverCommand
          content:
            application/3gppHal+json:
              schema:
                $ref: 'ETRI_Common_Data.yaml#/components/schemas/HandoverCommand'
        '400':
          description: HandoverRequestFailure
          content:
            application/json:
              schema:
                $ref: 'ETRI_Common_Data.yaml#/components/schemas/HandoverPreparationFailure'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
 
  /notify/{ueId}:
    put:
      operationId: HandoverNotify
      parameters:
        - name: ueId
          in: path
          required: true
          schema:
            type: integer
            format: int64

      requestBody:
        content:
          application/json:
            schema:
              $ref: 'ETRI_Common_Data.yaml#/components/schemas/HandoverNotify'
        required: true
      responses:
        '201':
          description: Success
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
 
  /cancel/{ueId}:
    put:
      operationId: HandoverCancel
      parameters:
        - name: ueId
          in: path
          required: true
          schema:
            type: integer
            format: int64

      requestBody:
        content:
          application/json:
            schema:
              $ref: 'ETRI_Common_Data.yaml#/components/schemas/HandoverCancel'
        required: true

      responses:
        '201':
          description: HandoverCancelAcknowledge
          content:
            application/json:
              schema:
                $ref: 'ETRI_Common_Data.yaml#/components/schemas/HandoverCancelAcknowledge'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
 
  /pathswitch/{ueId}:
    post:
      operationId: PathSwitch
      parameters:
        - name: callback
          in: header
          required: true
          schema:
            $ref: 'ETRI_Common_Data.yaml#/components/schemas/EndpointInfo'

        - name: ueId
          in: path
          required: true
          schema:
            type: integer
            format: int64

      requestBody:
        content:
          application/json:
            schema:
              $ref: 'ETRI_Common_Data.yaml#/components/schemas/PathSwitchRequest'
        required: true
      responses:
        '201':
          description: PathSwitchAcknowledge
          content:
            application/json:
              schema:
                $ref: 'ETRI_Common_Data.yaml#/components/schemas/PathSwitchAcknowledge'
        '400':
          description: PathSwitchFailure
          content:
            application/json:
              schema:
                $ref: 'ETRI_Common_Data.yaml#/components/schemas/PathSwitchFailure'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
 

components:
  securitySchemes:
  schemas:

