openapi: 3.0.0
info:
  version: 1.2.3
  title: AMF UeContext Management APIs
  description: |
    AMF UeContext management service
    © 2023, ETRI
    All rights reserved.
servers:
  - url: '{apiRoot}/amf-uectx/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501.

paths:
  /release/{ueId}:
    post:
      operationId: UeContextRelease
      parameters:
        - name: ueId
          in: path
          required: true
          schema:
            type: integer
            format: int64

      requestBody:
        content:
          application/json:
            schema:
              $ref: 'ETRI_Common_Data.yaml#/components/schemas/UeContextReleaseRequest'
        required: true
      responses:
        '201':
          description: Success
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
 
  /rrc/{ueId}:
    post:
      operationId: RrcInactivityStatusReport
      parameters:
        - name: ueId
          in: path
          required: true
          schema:
            type: integer
            format: int64

      requestBody:
        content:
          application/json:
            schema:
              $ref: 'ETRI_Common_Data.yaml#/components/schemas/RrcInactivityTransportReport'
        required: true
      responses:
        '201':
          description: Success
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'

  /n2sminfo/{ueId}:
    post:
      operationId: N2SmInfoUplink
      parameters:
        - name: ueId
          in: path
          required: true
          schema:
            type: integer
            format: int64

      requestBody:
        content:
          application/json:
            schema:
              $ref: 'ETRI_Common_Data.yaml#/components/schemas/N2SmInfoUplinkTransport'
        required: true
      responses:
        '201':
          description: Success
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
 

components:
  securitySchemes:
  schemas:

