openapi: 3.0.0
info:
  version: 1.0.0
  title: NSM Configuration Server APIs
  description: |
    NSM Configuration service
    © 2024, ETRI
    All rights reserved.
servers:
  - url: '{apiRoot}/nsm-conf/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501.

paths:
  /udr-config:
    get:
      operationId: GetUdrConfiguration
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UdrConfiguration'

        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'

  /udm-config:
    get:
      operationId: GetUdmConfiguration
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UdmConfiguration'

        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'


  /nssf-config:
    get:
      operationId: GetNssfConfiguration
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NssfConfiguration'

        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'

  /smf-config/{uuid}/{slice}:
    post:
      operationId: GetSessionManagementConfiguration
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
        - name: slice
          in: path
          required: true
          schema:
            $ref: 'TS29571_CommonData.yaml#/components/schemas/Snssai'

      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionManagementConfiguration'

        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
  /upf-config:
    get:
      operationId: GetUserPlaneConfiguration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPlaneConfigurationRequest'
        required: true

      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPlaneConfigurationResponse'

        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
  /sepp-config:
    get:
      operationId: GetSeppConfiguration
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SeppConfiguration'

        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'


components:
  securitySchemes:
  schemas:
    AmfSetConfiguration:
      description: Amf set configuration
      type: object
      properties:
        setId:
          type: string
        slices:
          type: array
          items:
            $ref: 'TS29571_CommonData.yaml#/components/schemas/Snssai'
      required:
        - setId

    NssfConfiguration:
      description: Nssf configuration
      type: object
      properties:
        amfSets:
          type: array
          items:
            $ref: '#/components/schemas/AmfSetConfiguration'
        slices:
          type: array
          items:
            $ref: '#/components/schemas/SliceConfiguration'
        plmnPeers:
          type: array
          items:
            $ref: '#/components/schemas/HomePlmnConfiguration'
      required:
        - amfSets

    DataNetworkConfiguration:
      description: Data network configuration
      type: object
      properties:
        name:
          type: string
        dns:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/IpAddr'
        pcscf:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/IpAddr'
        dhcpServer:
          type: string
        cidr:
          type: string
        ipRange:
          type: integer
          format: int64
        poolIndexList:
          type: array
          items:
            type: integer
            format: int16
      required:
        - name

    SessionManagementConfiguration:
      description: Session management configuration for an SMF
      type: object
      properties:
        transportNetworks:
          type: array
          items:
            type: string
        dataNetworks:
          type: array
          items:
            $ref: '#/components/schemas/DataNetworkConfiguration'
        slices:
          type: array
          items:
            $ref: '#/components/schemas/SliceConfiguration'

      required:
        - dataNetworks
        - transportNetworks
        - slices

    DataNetworkInfo:
      description: Data network Information
      type: object
      properties:
        name:
          type: string
        cidr:
          type: string
      required:
        - name
        - cidr

    UserPlaneConfigurationRequest:
      description: Request User Plane configuration from UPF
      type: object
      properties:
        slices:
          type: array
          items:
            $ref: 'TS29571_CommonData.yaml#/components/schemas/Snssai'
      required:
        - slices

    UserPlaneConfigurationResponse:
      description: User Plane configuration response to UPF
      type: object
      properties:
        transportNetworks:
          type: array
          items:
            type: string
        dataNetworks:
          type: array
          items:
            $ref: '#/components/schemas/DataNetworkInfo'
        slices:
          type: array
          items:
            $ref: '#/components/schemas/SliceConfiguration'


      required:
        - dataNetworks
        - transportNetworks
        - slices
    
    SliceConfiguration:
      description: Slice configuration
      type: object
      properties:
        id:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Snssai'
        dnnList:
          type: array
          items:
            type: string
      required:
        - id

    HomePlmnConfiguration:
      description: Home network configuration
      type: object
      properties:
        id:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/PlmnId'
        slices:
          type: array
          items:
            $ref: 'TS29531_Nnssf_NSSelection.yaml#/components/schemas/MappingOfSnssai'
        sepps:
          type: array
          items:
            type: string
      required:
        - id

    SuciProfile:
      description: SUCI profile
      type: object
      properties:
        protectionScheme:
          type: string
        publicKey:
          type: string
        privateKey:
          type: string
      required:
        - protectionScheme
        - publicKey
        - privateKey

    UdrConfiguration:
      description: Udr configuration
      type: object
      properties:
        dbName:
          type: string
        authSub:
          type: string
        amSub:
          type: string
        smSub:
          type: string
        smfSel:
          type: string
        url:
          type: string
        mock:
          type: boolean
      required:
        - dbName
        - authSub
        - url

    UdmConfiguration:
      description: Udm configuration
      type: object
      properties:
        udr:
          $ref: '#/components/schemas/UdrConfiguration'
        suciProfiles:
          type: array
          items:
            $ref: '#/components/schemas/SuciProfile'
      required:
        - udr
        - suciProfiles

    SeppConfiguration:
      description: Sepp configuration
      type: object
      properties:
        sepps:
          type: array
          items:
            $ref: '#/components/schemas/HomePlmnConfiguration'
      required:
        - sepps

