openapi: 3.0.0
info:
  version: 1.2.3
  title: PRAN AMF subscription APIs
  description: |
    PRAN AMF subscription service
    © 2023, ETRI
    All rights reserved.
servers:
  - url: '{apiRoot}/pran-amf/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501.

paths:
  /subscribe:
    post:
      operationId: AmfSubscribe
      parameters:
        - name: callback
          in: header
          required: true
          schema:
            $ref: 'ETRI_Common_Data.yaml#/components/schemas/EndpointInfo'

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AmfSubscribeRequest'
        required: true

      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AmfSubscribeResponse'

        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
  /paging:
    post:
      operationId: SendPaging
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PagingMessage'
        required: true

      responses:
        '201':
          description: Success

        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'


components:
  securitySchemes:
  schemas:

    SupportedTAItem:
      description: Supported TA item at gnB
      type: object
      properties:
        tac:
          type: string
        plmnList:
          type: array
          items:
            $ref: 'ETRI_NSM_Amf_Management.yaml#/components/schemas/SupportedPlmnItem'
      required:
        - tac


    AmfSubscribeRequest:
      description: AMF subscription request to PRAN
      type: object
      properties:
        id:
          type: string
      required:
        - id

    AmfSubscribeResponse:
      description: AMF subscription response from PRAN
      type: object
      properties:
        id:
          type: string
        plmnId:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/PlmnId'
        supportedTAList:
          type: array
          items:
            $ref: '#/components/schemas/SupportedTAItem'
      required:
        - id
        - plmnId

    PagingMessage:
      description: Paging message to gnB
      type: object
      properties:
        tmsi:
          type: integer
          format: int32
        amfSet:
          type: integer
          format: int16
        amfPointer:
          type: integer
          format: int16
        pagingOrigin:
          type: boolean
        taList:
          type: array
          items:
            $ref: 'TS29571_CommonData.yaml#/components/schemas/Tai'
      required:
        - tmsi
        - amfSet
        - amfPointer
        - gpp

