/*
This file is generated with a SBI APIs generator tool developed by ETRI
Generated at Thu Jun 12 16:32:15 KST 2025 by TungTQ<tqtung@etri.re.kr>
Do not modify
*/

package models

type AmfEventType string

// Define constant values for AmfEventType
const (
	AMFEVENTTYPE_LOCATION_REPORT                       AmfEventType = "LOCATION_REPORT"
	AMFEVENTTYPE_PRESENCE_IN_AOI_REPORT                AmfEventType = "PRESENCE_IN_AOI_REPORT"
	AMFEVENTTYPE_TIMEZONE_REPORT                       AmfEventType = "TIMEZONE_REPORT"
	AMFEVENTTYPE_ACCESS_TYPE_REPORT                    AmfEventType = "ACCESS_TYPE_REPORT"
	AMFEVENTTYPE_REGISTRATION_STATE_REPORT             AmfEventType = "REGISTRATION_STATE_REPORT"
	AMFEVENTTYPE_CONNECTIVITY_STATE_REPORT             AmfEventType = "CONNECTIVITY_STATE_REPORT"
	AMFEVENTTYPE_REACHABILITY_REPORT                   AmfEventType = "REACHABILITY_REPORT"
	AMFEVENTTYPE_COMMUNICATION_FAILURE_REPORT          AmfEventType = "COMMUNICATION_FAILURE_REPORT"
	AMFEVENTTYPE_UES_IN_AREA_REPORT                    AmfEventType = "UES_IN_AREA_REPORT"
	AMFEVENTTYPE_SUBSCRIPTION_ID_CHANGE                AmfEventType = "SUBSCRIPTION_ID_CHANGE"
	AMFEVENTTYPE_SUBSCRIPTION_ID_ADDITION              AmfEventType = "SUBSCRIPTION_ID_ADDITION"
	AMFEVENTTYPE_LOSS_OF_CONNECTIVITY                  AmfEventType = "LOSS_OF_CONNECTIVITY"
	AMFEVENTTYPE_5GS_USER_STATE_REPORT                 AmfEventType = "5GS_USER_STATE_REPORT"
	AMFEVENTTYPE_AVAILABILITY_AFTER_DDN_FAILURE        AmfEventType = "AVAILABILITY_AFTER_DDN_FAILURE"
	AMFEVENTTYPE_TYPE_ALLOCATION_CODE_REPORT           AmfEventType = "TYPE_ALLOCATION_CODE_REPORT"
	AMFEVENTTYPE_FREQUENT_MOBILITY_REGISTRATION_REPORT AmfEventType = "FREQUENT_MOBILITY_REGISTRATION_REPORT"
	AMFEVENTTYPE_SNSSAI_TA_MAPPING_REPORT              AmfEventType = "SNSSAI_TA_MAPPING_REPORT"
	AMFEVENTTYPE_UE_LOCATION_TRENDS                    AmfEventType = "UE_LOCATION_TRENDS"
	AMFEVENTTYPE_UE_ACCESS_BEHAVIOR_TRENDS             AmfEventType = "UE_ACCESS_BEHAVIOR_TRENDS"
	AMFEVENTTYPE_UE_MM_TRANSACTION_REPORT              AmfEventType = "UE_MM_TRANSACTION_REPORT"
)
