/*
This file is generated with a SBI APIs generator tool developed by ETRI
Generated at Tue Jul 22 12:00:22 KST 2025 by TungTQ<tqtung@etri.re.kr>
Do not modify
*/

package models

type Cause string

// Define constant values for Cause
const (
	CAUSE_REL_DUE_TO_HO                     Cause = "REL_DUE_TO_HO"
	CAUSE_EPS_FALLBACK                      Cause = "EPS_FALLBACK"
	CAUSE_REL_DUE_TO_UP_SEC                 Cause = "REL_DUE_TO_UP_SEC"
	CAUSE_DNN_CONGESTION                    Cause = "DNN_CONGESTION"
	CAUSE_S_NSSAI_CONGESTION                Cause = "S_NSSAI_CONGESTION"
	CAUSE_REL_DUE_TO_REACTIVATION           Cause = "REL_DUE_TO_REACTIVATION"
	CAUSE_5G_AN_NOT_RESPONDING              Cause = "5G_AN_NOT_RESPONDING"
	CAUSE_REL_DUE_TO_SLICE_NOT_AVAILABLE    Cause = "REL_DUE_TO_SLICE_NOT_AVAILABLE"
	CAUSE_REL_DUE_TO_DUPLICATE_SESSION_ID   Cause = "REL_DUE_TO_DUPLICATE_SESSION_ID"
	CAUSE_PDU_SESSION_STATUS_MISMATCH       Cause = "PDU_SESSION_STATUS_MISMATCH"
	CAUSE_HO_FAILURE                        Cause = "HO_FAILURE"
	CAUSE_INSUFFICIENT_UP_RESOURCES         Cause = "INSUFFICIENT_UP_RESOURCES"
	CAUSE_PDU_SESSION_HANDED_OVER           Cause = "PDU_SESSION_HANDED_OVER"
	CAUSE_PDU_SESSION_RESUMED               Cause = "PDU_SESSION_RESUMED"
	CAUSE_CN_ASSISTED_RAN_PARAMETER_TUNING  Cause = "CN_ASSISTED_RAN_PARAMETER_TUNING"
	CAUSE_ISMF_CONTEXT_TRANSFER             Cause = "ISMF_CONTEXT_TRANSFER"
	CAUSE_SMF_CONTEXT_TRANSFER              Cause = "SMF_CONTEXT_TRANSFER"
	CAUSE_REL_DUE_TO_PS_TO_CS_HO            Cause = "REL_DUE_TO_PS_TO_CS_HO"
	CAUSE_REL_DUE_TO_SUBSCRIPTION_CHANGE    Cause = "REL_DUE_TO_SUBSCRIPTION_CHANGE"
	CAUSE_HO_CANCEL                         Cause = "HO_CANCEL"
	CAUSE_REL_DUE_TO_SLICE_NOT_AUTHORIZED   Cause = "REL_DUE_TO_SLICE_NOT_AUTHORIZED"
	CAUSE_PDU_SESSION_HAND_OVER_FAILURE     Cause = "PDU_SESSION_HAND_OVER_FAILURE"
	CAUSE_DDN_FAILURE_STATUS                Cause = "DDN_FAILURE_STATUS"
	CAUSE_REL_DUE_TO_CP_ONLY_NOT_APPLICABLE Cause = "REL_DUE_TO_CP_ONLY_NOT_APPLICABLE"
	CAUSE_NOT_SUPPORTED_WITH_ISMF           Cause = "NOT_SUPPORTED_WITH_ISMF"
	CAUSE_CHANGED_ANCHOR_SMF                Cause = "CHANGED_ANCHOR_SMF"
	CAUSE_CHANGED_INTERMEDIATE_SMF          Cause = "CHANGED_INTERMEDIATE_SMF"
	CAUSE_TARGET_DNAI_NOTIFICATION          Cause = "TARGET_DNAI_NOTIFICATION"
	CAUSE_REL_DUE_TO_VPLMN_QOS_FAILURE      Cause = "REL_DUE_TO_VPLMN_QOS_FAILURE"
	CAUSE_REL_DUE_TO_SMF_NOT_SUPPORT_PSETR  Cause = "REL_DUE_TO_SMF_NOT_SUPPORT_PSETR"
	CAUSE_REL_DUE_TO_SNPN_SNPN_MOBILITY     Cause = "REL_DUE_TO_SNPN_SNPN_MOBILITY"
	CAUSE_REL_DUE_TO_NO_HR_AGREEMENT        Cause = "REL_DUE_TO_NO_HR_AGREEMENT"
	CAUSE_REL_DUE_TO_UNSPECIFIED_REASON     Cause = "REL_DUE_TO_UNSPECIFIED_REASON"
)
