/*
This file is generated with a SBI APIs generator tool developed by ETRI
Generated at Fri Jun 13 13:39:29 KST 2025 by TungTQ<tqtung@etri.re.kr>
Do not modify
*/

package models

type EventType string

// Define constant values for EventType
const (
	EVENTTYPE_LOSS_OF_CONNECTIVITY                  EventType = "LOSS_OF_CONNECTIVITY"
	EVENTTYPE_UE_REACHABILITY_FOR_DATA              EventType = "UE_REACHABILITY_FOR_DATA"
	EVENTTYPE_UE_REACHABILITY_FOR_SMS               EventType = "UE_REACHABILITY_FOR_SMS"
	EVENTTYPE_LOCATION_REPORTING                    EventType = "LOCATION_REPORTING"
	EVENTTYPE_CHANGE_OF_SUPI_PEI_ASSOCIATION        EventType = "CHANGE_OF_SUPI_PEI_ASSOCIATION"
	EVENTTYPE_ROAMING_STATUS                        EventType = "ROAMING_STATUS"
	EVENTTYPE_COMMUNICATION_FAILURE                 EventType = "COMMUNICATION_FAILURE"
	EVENTTYPE_AVAILABILITY_AFTER_DDN_FAILURE        EventType = "AVAILABILITY_AFTER_DDN_FAILURE"
	EVENTTYPE_CN_TYPE_CHANGE                        EventType = "CN_TYPE_CHANGE"
	EVENTTYPE_DL_DATA_DELIVERY_STATUS               EventType = "DL_DATA_DELIVERY_STATUS"
	EVENTTYPE_PDN_CONNECTIVITY_STATUS               EventType = "PDN_CONNECTIVITY_STATUS"
	EVENTTYPE_UE_CONNECTION_MANAGEMENT_STATE        EventType = "UE_CONNECTION_MANAGEMENT_STATE"
	EVENTTYPE_ACCESS_TYPE_REPORT                    EventType = "ACCESS_TYPE_REPORT"
	EVENTTYPE_REGISTRATION_STATE_REPORT             EventType = "REGISTRATION_STATE_REPORT"
	EVENTTYPE_CONNECTIVITY_STATE_REPORT             EventType = "CONNECTIVITY_STATE_REPORT"
	EVENTTYPE_TYPE_ALLOCATION_CODE_REPORT           EventType = "TYPE_ALLOCATION_CODE_REPORT"
	EVENTTYPE_FREQUENT_MOBILITY_REGISTRATION_REPORT EventType = "FREQUENT_MOBILITY_REGISTRATION_REPORT"
	EVENTTYPE_PDU_SES_REL                           EventType = "PDU_SES_REL"
	EVENTTYPE_PDU_SES_EST                           EventType = "PDU_SES_EST"
	EVENTTYPE_UE_MEMORY_AVAILABLE_FOR_SMS           EventType = "UE_MEMORY_AVAILABLE_FOR_SMS"
)
