/*
This file is generated with a SBI APIs generator tool developed by ETRI
Generated at Thu Jun 12 16:32:15 KST 2025 by TungTQ<tqtung@etri.re.kr>
Do not modify
*/

package models

type ExceptionId string

// Define constant values for ExceptionId
const (
	EXCEPTIONID_UNEXPECTED_UE_LOCATION         ExceptionId = "UNEXPECTED_UE_LOCATION"
	EXCEPTIONID_UNEXPECTED_LONG_LIVE_FLOW      ExceptionId = "UNEXPECTED_LONG_LIVE_FLOW"
	EXCEPTIONID_UNEXPECTED_LARGE_RATE_FLOW     ExceptionId = "UNEXPECTED_LARGE_RATE_FLOW"
	EXCEPTIONID_UNEXPECTED_WAKEUP              ExceptionId = "UNEXPECTED_WAKEUP"
	EXCEPTIONID_SUSPICION_OF_DDOS_ATTACK       ExceptionId = "SUSPICION_OF_DDOS_ATTACK"
	EXCEPTIONID_WRONG_DESTINATION_ADDRESS      ExceptionId = "WRONG_DESTINATION_ADDRESS"
	EXCEPTIONID_TOO_FREQUENT_SERVICE_ACCESS    ExceptionId = "TOO_FREQUENT_SERVICE_ACCESS"
	EXCEPTIONID_UNEXPECTED_RADIO_LINK_FAILURES ExceptionId = "UNEXPECTED_RADIO_LINK_FAILURES"
	EXCEPTIONID_PING_PONG_ACROSS_CELLS         ExceptionId = "PING_PONG_ACROSS_CELLS"
)
