/*
This file is generated with a SBI APIs generator tool developed by ETRI
Generated at Tue Jul  8 13:19:45 KST 2025 by TungTQ<tqtung@etri.re.kr>
Do not modify
*/

package models

type N1N2MessageTransferCause string

// Define constant values for N1N2MessageTransferCause
const (
	N1N2MESSAGETRANSFERCAUSE_ATTEMPTING_TO_REACH_UE                N1N2MessageTransferCause = "ATTEMPTING_TO_REACH_UE"
	N1N2MESSAGETRANSFERCAUSE_N1_N2_TRANSFER_INITIATED              N1N2MessageTransferCause = "N1_N2_TRANSFER_INITIATED"
	N1N2MESSAGETRANSFERCAUSE_WAITING_FOR_ASYNCHRONOUS_TRANSFER     N1N2MessageTransferCause = "WAITING_FOR_ASYNCHRONOUS_TRANSFER"
	N1N2MESSAGETRANSFERCAUSE_UE_NOT_RESPONDING                     N1N2MessageTransferCause = "UE_NOT_RESPONDING"
	N1N2MESSAGETRANSFERCAUSE_N1_MSG_NOT_TRANSFERRED                N1N2MessageTransferCause = "N1_MSG_NOT_TRANSFERRED"
	N1N2MESSAGETRANSFERCAUSE_N2_MSG_NOT_TRANSFERRED                N1N2MessageTransferCause = "N2_MSG_NOT_TRANSFERRED"
	N1N2MESSAGETRANSFERCAUSE_UE_NOT_REACHABLE_FOR_SESSION          N1N2MessageTransferCause = "UE_NOT_REACHABLE_FOR_SESSION"
	N1N2MESSAGETRANSFERCAUSE_TEMPORARY_REJECT_REGISTRATION_ONGOING N1N2MessageTransferCause = "TEMPORARY_REJECT_REGISTRATION_ONGOING"
	N1N2MESSAGETRANSFERCAUSE_TEMPORARY_REJECT_HANDOVER_ONGOING     N1N2MessageTransferCause = "TEMPORARY_REJECT_HANDOVER_ONGOING"
	N1N2MESSAGETRANSFERCAUSE_REJECTION_DUE_TO_PAGING_RESTRICTION   N1N2MessageTransferCause = "REJECTION_DUE_TO_PAGING_RESTRICTION"
	N1N2MESSAGETRANSFERCAUSE_AN_NOT_RESPONDING                     N1N2MessageTransferCause = "AN_NOT_RESPONDING"
	N1N2MESSAGETRANSFERCAUSE_FAILURE_CAUSE_UNSPECIFIED             N1N2MessageTransferCause = "FAILURE_CAUSE_UNSPECIFIED"
)
