/*
This file is generated with a SBI APIs generator tool developed by ETRI
Generated at Fri Jun 13 11:41:41 KST 2025 by TungTQ<tqtung@etri.re.kr>
Do not modify
*/

package models

type N2SmInfoType string

// Define constant values for N2SmInfoType
const (
	N2SMINFOTYPE_PDU_RES_SETUP_REQ       N2SmInfoType = "PDU_RES_SETUP_REQ"
	N2SMINFOTYPE_PDU_RES_SETUP_RSP       N2SmInfoType = "PDU_RES_SETUP_RSP"
	N2SMINFOTYPE_PDU_RES_SETUP_FAIL      N2SmInfoType = "PDU_RES_SETUP_FAIL"
	N2SMINFOTYPE_PDU_RES_REL_CMD         N2SmInfoType = "PDU_RES_REL_CMD"
	N2SMINFOTYPE_PDU_RES_REL_RSP         N2SmInfoType = "PDU_RES_REL_RSP"
	N2SMINFOTYPE_PDU_RES_MOD_REQ         N2SmInfoType = "PDU_RES_MOD_REQ"
	N2SMINFOTYPE_PDU_RES_MOD_RSP         N2SmInfoType = "PDU_RES_MOD_RSP"
	N2SMINFOTYPE_PDU_RES_MOD_FAIL        N2SmInfoType = "PDU_RES_MOD_FAIL"
	N2SMINFOTYPE_PDU_RES_NTY             N2SmInfoType = "PDU_RES_NTY"
	N2SMINFOTYPE_PDU_RES_NTY_REL         N2SmInfoType = "PDU_RES_NTY_REL"
	N2SMINFOTYPE_PDU_RES_MOD_IND         N2SmInfoType = "PDU_RES_MOD_IND"
	N2SMINFOTYPE_PDU_RES_MOD_CFM         N2SmInfoType = "PDU_RES_MOD_CFM"
	N2SMINFOTYPE_PATH_SWITCH_REQ         N2SmInfoType = "PATH_SWITCH_REQ"
	N2SMINFOTYPE_PATH_SWITCH_SETUP_FAIL  N2SmInfoType = "PATH_SWITCH_SETUP_FAIL"
	N2SMINFOTYPE_PATH_SWITCH_REQ_ACK     N2SmInfoType = "PATH_SWITCH_REQ_ACK"
	N2SMINFOTYPE_PATH_SWITCH_REQ_FAIL    N2SmInfoType = "PATH_SWITCH_REQ_FAIL"
	N2SMINFOTYPE_HANDOVER_REQUIRED       N2SmInfoType = "HANDOVER_REQUIRED"
	N2SMINFOTYPE_HANDOVER_CMD            N2SmInfoType = "HANDOVER_CMD"
	N2SMINFOTYPE_HANDOVER_PREP_FAIL      N2SmInfoType = "HANDOVER_PREP_FAIL"
	N2SMINFOTYPE_HANDOVER_REQ_ACK        N2SmInfoType = "HANDOVER_REQ_ACK"
	N2SMINFOTYPE_HANDOVER_RES_ALLOC_FAIL N2SmInfoType = "HANDOVER_RES_ALLOC_FAIL"
	N2SMINFOTYPE_SECONDARY_RAT_USAGE     N2SmInfoType = "SECONDARY_RAT_USAGE"
	N2SMINFOTYPE_PDU_RES_MOD_IND_FAIL    N2SmInfoType = "PDU_RES_MOD_IND_FAIL"
	N2SMINFOTYPE_UE_CONTEXT_RESUME_REQ   N2SmInfoType = "UE_CONTEXT_RESUME_REQ"
	N2SMINFOTYPE_UE_CONTEXT_RESUME_RSP   N2SmInfoType = "UE_CONTEXT_RESUME_RSP"
	N2SMINFOTYPE_UE_CONTEXT_SUSPEND_REQ  N2SmInfoType = "UE_CONTEXT_SUSPEND_REQ"
)
