/*
This file is generated with a SBI APIs generator tool developed by ETRI
Generated at Wed May 14 15:26:45 KST 2025 by TungTQ<tqtung@etri.re.kr>
Do not modify
*/

package models

type NFType string

// Define constant values for NFType
const (
	NFTYPE_NRF        NFType = "NRF"
	NFTYPE_UDM        NFType = "UDM"
	NFTYPE_AMF        NFType = "AMF"
	NFTYPE_SMF        NFType = "SMF"
	NFTYPE_AUSF       NFType = "AUSF"
	NFTYPE_NEF        NFType = "NEF"
	NFTYPE_PCF        NFType = "PCF"
	NFTYPE_SMSF       NFType = "SMSF"
	NFTYPE_NSSF       NFType = "NSSF"
	NFTYPE_UDR        NFType = "UDR"
	NFTYPE_LMF        NFType = "LMF"
	NFTYPE_GMLC       NFType = "GMLC"
	NFTYPE_5G_EIR     NFType = "5G_EIR"
	NFTYPE_SEPP       NFType = "SEPP"
	NFTYPE_UPF        NFType = "UPF"
	NFTYPE_N3IWF      NFType = "N3IWF"
	NFTYPE_AF         NFType = "AF"
	NFTYPE_UDSF       NFType = "UDSF"
	NFTYPE_BSF        NFType = "BSF"
	NFTYPE_CHF        NFType = "CHF"
	NFTYPE_NWDAF      NFType = "NWDAF"
	NFTYPE_PCSCF      NFType = "PCSCF"
	NFTYPE_CBCF       NFType = "CBCF"
	NFTYPE_HSS        NFType = "HSS"
	NFTYPE_UCMF       NFType = "UCMF"
	NFTYPE_SOR_AF     NFType = "SOR_AF"
	NFTYPE_SPAF       NFType = "SPAF"
	NFTYPE_MME        NFType = "MME"
	NFTYPE_SCSAS      NFType = "SCSAS"
	NFTYPE_SCEF       NFType = "SCEF"
	NFTYPE_SCP        NFType = "SCP"
	NFTYPE_NSSAAF     NFType = "NSSAAF"
	NFTYPE_ICSCF      NFType = "ICSCF"
	NFTYPE_SCSCF      NFType = "SCSCF"
	NFTYPE_DRA        NFType = "DRA"
	NFTYPE_IMS_AS     NFType = "IMS_AS"
	NFTYPE_AANF       NFType = "AANF"
	NFTYPE_5G_DDNMF   NFType = "5G_DDNMF"
	NFTYPE_NSACF      NFType = "NSACF"
	NFTYPE_MFAF       NFType = "MFAF"
	NFTYPE_EASDF      NFType = "EASDF"
	NFTYPE_DCCF       NFType = "DCCF"
	NFTYPE_MB_SMF     NFType = "MB_SMF"
	NFTYPE_TSCTSF     NFType = "TSCTSF"
	NFTYPE_ADRF       NFType = "ADRF"
	NFTYPE_GBA_BSF    NFType = "GBA_BSF"
	NFTYPE_CEF        NFType = "CEF"
	NFTYPE_MB_UPF     NFType = "MB_UPF"
	NFTYPE_NSWOF      NFType = "NSWOF"
	NFTYPE_PKMF       NFType = "PKMF"
	NFTYPE_MNPF       NFType = "MNPF"
	NFTYPE_SMS_GMSC   NFType = "SMS_GMSC"
	NFTYPE_SMS_IWMSC  NFType = "SMS_IWMSC"
	NFTYPE_MBSF       NFType = "MBSF"
	NFTYPE_MBSTF      NFType = "MBSTF"
	NFTYPE_PANF       NFType = "PANF"
	NFTYPE_IP_SM_GW   NFType = "IP_SM_GW"
	NFTYPE_SMS_ROUTER NFType = "SMS_ROUTER"
)
