/*
This file is generated with a SBI APIs generator tool developed by ETRI
Generated at Tue Jun 17 13:36:01 KST 2025 by TungTQ<tqtung@etri.re.kr>
Do not modify
*/

package models

type NgapIeType string

// Define constant values for NgapIeType
const (
	NGAPIETYPE_PDU_RES_SETUP_REQ              NgapIeType = "PDU_RES_SETUP_REQ"
	NGAPIETYPE_PDU_RES_REL_CMD                NgapIeType = "PDU_RES_REL_CMD"
	NGAPIETYPE_PDU_RES_MOD_REQ                NgapIeType = "PDU_RES_MOD_REQ"
	NGAPIETYPE_HANDOVER_CMD                   NgapIeType = "HANDOVER_CMD"
	NGAPIETYPE_HANDOVER_REQUIRED              NgapIeType = "HANDOVER_REQUIRED"
	NGAPIETYPE_HANDOVER_PREP_FAIL             NgapIeType = "HANDOVER_PREP_FAIL"
	NGAPIETYPE_SRC_TO_TAR_CONTAINER           NgapIeType = "SRC_TO_TAR_CONTAINER"
	NGAPIETYPE_TAR_TO_SRC_CONTAINER           NgapIeType = "TAR_TO_SRC_CONTAINER"
	NGAPIETYPE_TAR_TO_SRC_FAIL_CONTAINER      NgapIeType = "TAR_TO_SRC_FAIL_CONTAINER"
	NGAPIETYPE_RAN_STATUS_TRANS_CONTAINER     NgapIeType = "RAN_STATUS_TRANS_CONTAINER"
	NGAPIETYPE_SON_CONFIG_TRANSFER            NgapIeType = "SON_CONFIG_TRANSFER"
	NGAPIETYPE_NRPPA_PDU                      NgapIeType = "NRPPA_PDU"
	NGAPIETYPE_UE_RADIO_CAPABILITY            NgapIeType = "UE_RADIO_CAPABILITY"
	NGAPIETYPE_RIM_INFO_TRANSFER              NgapIeType = "RIM_INFO_TRANSFER"
	NGAPIETYPE_SECONDARY_RAT_USAGE            NgapIeType = "SECONDARY_RAT_USAGE"
	NGAPIETYPE_PC5_QOS_PARA                   NgapIeType = "PC5_QOS_PARA"
	NGAPIETYPE_EARLY_STATUS_TRANS_CONTAINER   NgapIeType = "EARLY_STATUS_TRANS_CONTAINER"
	NGAPIETYPE_UE_RADIO_CAPABILITY_FOR_PAGING NgapIeType = "UE_RADIO_CAPABILITY_FOR_PAGING"
)
