/*
This file is generated with a SBI APIs generator tool developed by ETRI
Generated at Tue Jun 17 13:36:00 KST 2025 by TungTQ<tqtung@etri.re.kr>
Do not modify
*/

package models

type NwdafEvent string

// Define constant values for NwdafEvent
const (
	NWDAFEVENT_SLICE_LOAD_LEVEL     NwdafEvent = "SLICE_LOAD_LEVEL"
	NWDAFEVENT_NETWORK_PERFORMANCE  NwdafEvent = "NETWORK_PERFORMANCE"
	NWDAFEVENT_NF_LOAD              NwdafEvent = "NF_LOAD"
	NWDAFEVENT_SERVICE_EXPERIENCE   NwdafEvent = "SERVICE_EXPERIENCE"
	NWDAFEVENT_UE_MOBILITY          NwdafEvent = "UE_MOBILITY"
	NWDAFEVENT_UE_COMMUNICATION     NwdafEvent = "UE_COMMUNICATION"
	NWDAFEVENT_QOS_SUSTAINABILITY   NwdafEvent = "QOS_SUSTAINABILITY"
	NWDAFEVENT_ABNORMAL_BEHAVIOUR   NwdafEvent = "ABNORMAL_BEHAVIOUR"
	NWDAFEVENT_USER_DATA_CONGESTION NwdafEvent = "USER_DATA_CONGESTION"
	NWDAFEVENT_NSI_LOAD_LEVEL       NwdafEvent = "NSI_LOAD_LEVEL"
	NWDAFEVENT_DN_PERFORMANCE       NwdafEvent = "DN_PERFORMANCE"
	NWDAFEVENT_DISPERSION           NwdafEvent = "DISPERSION"
	NWDAFEVENT_RED_TRANS_EXP        NwdafEvent = "RED_TRANS_EXP"
	NWDAFEVENT_WLAN_PERFORMANCE     NwdafEvent = "WLAN_PERFORMANCE"
	NWDAFEVENT_SM_CONGESTION        NwdafEvent = "SM_CONGESTION"
)
