/*
This file is generated with a SBI APIs generator tool developed by ETRI
Generated at Sat Dec  7 16:57:33 KST 2024 by TungTQ<tqtung@etri.re.kr>
Do not modify
*/

package models

type PrivacyCheckRelatedAction string

// Define constant values for PrivacyCheckRelatedAction
const (
	PRIVACYCHECKRELATEDACTION_LOCATION_NOT_ALLOWED                  PrivacyCheckRelatedAction = "LOCATION_NOT_ALLOWED"
	PRIVACYCHECKRELATEDACTION_LOCATION_ALLOWED_WITH_NOTIFICATION    PrivacyCheckRelatedAction = "LOCATION_ALLOWED_WITH_NOTIFICATION"
	PRIVACYCHECKRELATEDACTION_LOCATION_ALLOWED_WITHOUT_NOTIFICATION PrivacyCheckRelatedAction = "LOCATION_ALLOWED_WITHOUT_NOTIFICATION"
	PRIVACYCHECKRELATEDACTION_LOCATION_ALLOWED_WITHOUT_RESPONSE     PrivacyCheckRelatedAction = "LOCATION_ALLOWED_WITHOUT_RESPONSE"
	PRIVACYCHECKRELATEDACTION_LOCATION_RESTRICTED_WITHOUT_RESPONSE  PrivacyCheckRelatedAction = "LOCATION_RESTRICTED_WITHOUT_RESPONSE"
)
