/*
This file is generated with a SBI APIs generator tool developed by ETRI
Generated at Fri Jun 13 13:39:29 KST 2025 by TungTQ<tqtung@etri.re.kr>
Do not modify
*/

package models

type ServiceName string

// Define constant values for ServiceName
const (
	SERVICENAME_NNRF_NFM                         ServiceName = "nnrf-nfm"
	SERVICENAME_NNRF_DISC                        ServiceName = "nnrf-disc"
	SERVICENAME_NNRF_OAUTH2                      ServiceName = "nnrf-oauth2"
	SERVICENAME_NUDM_SDM                         ServiceName = "nudm-sdm"
	SERVICENAME_NUDM_UECM                        ServiceName = "nudm-uecm"
	SERVICENAME_NUDM_UEAU                        ServiceName = "nudm-ueau"
	SERVICENAME_NUDM_EE                          ServiceName = "nudm-ee"
	SERVICENAME_NUDM_PP                          ServiceName = "nudm-pp"
	SERVICENAME_NUDM_NIDDAU                      ServiceName = "nudm-niddau"
	SERVICENAME_NUDM_MT                          ServiceName = "nudm-mt"
	SERVICENAME_NUDM_SSAU                        ServiceName = "nudm-ssau"
	SERVICENAME_NUDM_RSDS                        ServiceName = "nudm-rsds"
	SERVICENAME_NUDM_UEID                        ServiceName = "nudm-ueid"
	SERVICENAME_NAMF_COMM                        ServiceName = "namf-comm"
	SERVICENAME_NAMF_EVTS                        ServiceName = "namf-evts"
	SERVICENAME_NAMF_MT                          ServiceName = "namf-mt"
	SERVICENAME_NAMF_LOC                         ServiceName = "namf-loc"
	SERVICENAME_NAMF_MBS_COMM                    ServiceName = "namf-mbs-comm"
	SERVICENAME_NAMF_MBS_BC                      ServiceName = "namf-mbs-bc"
	SERVICENAME_NSMF_PDUSESSION                  ServiceName = "nsmf-pdusession"
	SERVICENAME_NSMF_EVENT_EXPOSURE              ServiceName = "nsmf-event-exposure"
	SERVICENAME_NSMF_NIDD                        ServiceName = "nsmf-nidd"
	SERVICENAME_NAUSF_AUTH                       ServiceName = "nausf-auth"
	SERVICENAME_NAUSF_SORPROTECTION              ServiceName = "nausf-sorprotection"
	SERVICENAME_NAUSF_UPUPROTECTION              ServiceName = "nausf-upuprotection"
	SERVICENAME_NNEF_PFDMANAGEMENT               ServiceName = "nnef-pfdmanagement"
	SERVICENAME_NNEF_SMCONTEXT                   ServiceName = "nnef-smcontext"
	SERVICENAME_NNEF_EVENTEXPOSURE               ServiceName = "nnef-eventexposure"
	SERVICENAME_NNEF_EAS_DEPLOYMENT              ServiceName = "nnef-eas-deployment"
	SERVICENAME_3GPP_CP_PARAMETER_PROVISIONING   ServiceName = "3gpp-cp-parameter-provisioning"
	SERVICENAME_3GPP_DEVICE_TRIGGERING           ServiceName = "3gpp-device-triggering"
	SERVICENAME_3GPP_BDT                         ServiceName = "3gpp-bdt"
	SERVICENAME_3GPP_TRAFFIC_INFLUENCE           ServiceName = "3gpp-traffic-influence"
	SERVICENAME_3GPP_CHARGEABLE_PARTY            ServiceName = "3gpp-chargeable-party"
	SERVICENAME_3GPP_AS_SESSION_WITH_QOS         ServiceName = "3gpp-as-session-with-qos"
	SERVICENAME_3GPP_MSISDN_LESS_MO_SMS          ServiceName = "3gpp-msisdn-less-mo-sms"
	SERVICENAME_3GPP_SERVICE_PARAMETER           ServiceName = "3gpp-service-parameter"
	SERVICENAME_3GPP_MONITORING_EVENT            ServiceName = "3gpp-monitoring-event"
	SERVICENAME_3GPP_NIDD_CONFIGURATION_TRIGGER  ServiceName = "3gpp-nidd-configuration-trigger"
	SERVICENAME_3GPP_NIDD                        ServiceName = "3gpp-nidd"
	SERVICENAME_3GPP_ANALYTICSEXPOSURE           ServiceName = "3gpp-analyticsexposure"
	SERVICENAME_3GPP_RACS_PARAMETER_PROVISIONING ServiceName = "3gpp-racs-parameter-provisioning"
	SERVICENAME_3GPP_ECR_CONTROL                 ServiceName = "3gpp-ecr-control"
	SERVICENAME_3GPP_APPLYING_BDT_POLICY         ServiceName = "3gpp-applying-bdt-policy"
	SERVICENAME_3GPP_MO_LCS_NOTIFY               ServiceName = "3gpp-mo-lcs-notify"
	SERVICENAME_3GPP_TIME_SYNC                   ServiceName = "3gpp-time-sync"
	SERVICENAME_3GPP_AM_INFLUENCE                ServiceName = "3gpp-am-influence"
	SERVICENAME_3GPP_AM_POLICYAUTHORIZATION      ServiceName = "3gpp-am-policyauthorization"
	SERVICENAME_3GPP_AKMA                        ServiceName = "3gpp-akma"
	SERVICENAME_3GPP_EAS_DEPLOYMENT              ServiceName = "3gpp-eas-deployment"
	SERVICENAME_3GPP_IPTVCONFIGURATION           ServiceName = "3gpp-iptvconfiguration"
	SERVICENAME_3GPP_MBS_TMGI                    ServiceName = "3gpp-mbs-tmgi"
	SERVICENAME_3GPP_MBS_SESSION                 ServiceName = "3gpp-mbs-session"
	SERVICENAME_3GPP_AUTHENTICATION              ServiceName = "3gpp-authentication"
	SERVICENAME_3GPP_ASTI                        ServiceName = "3gpp-asti"
	SERVICENAME_NPCF_AM_POLICY_CONTROL           ServiceName = "npcf-am-policy-control"
	SERVICENAME_NPCF_SMPOLICYCONTROL             ServiceName = "npcf-smpolicycontrol"
	SERVICENAME_NPCF_POLICYAUTHORIZATION         ServiceName = "npcf-policyauthorization"
	SERVICENAME_NPCF_BDTPOLICYCONTROL            ServiceName = "npcf-bdtpolicycontrol"
	SERVICENAME_NPCF_EVENTEXPOSURE               ServiceName = "npcf-eventexposure"
	SERVICENAME_NPCF_UE_POLICY_CONTROL           ServiceName = "npcf-ue-policy-control"
	SERVICENAME_NPCF_AM_POLICYAUTHORIZATION      ServiceName = "npcf-am-policyauthorization"
	SERVICENAME_NPCF_MBSPOLICYCONTROL            ServiceName = "npcf-mbspolicycontrol"
	SERVICENAME_NPCF_MBSPOLICYAUTH               ServiceName = "npcf-mbspolicyauth"
	SERVICENAME_NSMSF_SMS                        ServiceName = "nsmsf-sms"
	SERVICENAME_NNSSF_NSSELECTION                ServiceName = "nnssf-nsselection"
	SERVICENAME_NNSSF_NSSAIAVAILABILITY          ServiceName = "nnssf-nssaiavailability"
	SERVICENAME_NUDR_DR                          ServiceName = "nudr-dr"
	SERVICENAME_NUDR_GROUP_ID_MAP                ServiceName = "nudr-group-id-map"
	SERVICENAME_NLMF_LOC                         ServiceName = "nlmf-loc"
	SERVICENAME_N5G_EIR_EIC                      ServiceName = "n5g-eir-eic"
	SERVICENAME_NBSF_MANAGEMENT                  ServiceName = "nbsf-management"
	SERVICENAME_NCHF_SPENDINGLIMITCONTROL        ServiceName = "nchf-spendinglimitcontrol"
	SERVICENAME_NCHF_CONVERGEDCHARGING           ServiceName = "nchf-convergedcharging"
	SERVICENAME_NCHF_OFFLINEONLYCHARGING         ServiceName = "nchf-offlineonlycharging"
	SERVICENAME_NNWDAF_EVENTSSUBSCRIPTION        ServiceName = "nnwdaf-eventssubscription"
	SERVICENAME_NNWDAF_ANALYTICSINFO             ServiceName = "nnwdaf-analyticsinfo"
	SERVICENAME_NNWDAF_DATAMANAGEMENT            ServiceName = "nnwdaf-datamanagement"
	SERVICENAME_NNWDAF_MLMODELPROVISION          ServiceName = "nnwdaf-mlmodelprovision"
	SERVICENAME_NGMLC_LOC                        ServiceName = "ngmlc-loc"
	SERVICENAME_NUCMF_PROVISIONING               ServiceName = "nucmf-provisioning"
	SERVICENAME_NUCMF_UECAPABILITYMANAGEMENT     ServiceName = "nucmf-uecapabilitymanagement"
	SERVICENAME_NHSS_SDM                         ServiceName = "nhss-sdm"
	SERVICENAME_NHSS_UECM                        ServiceName = "nhss-uecm"
	SERVICENAME_NHSS_UEAU                        ServiceName = "nhss-ueau"
	SERVICENAME_NHSS_EE                          ServiceName = "nhss-ee"
	SERVICENAME_NHSS_IMS_SDM                     ServiceName = "nhss-ims-sdm"
	SERVICENAME_NHSS_IMS_UECM                    ServiceName = "nhss-ims-uecm"
	SERVICENAME_NHSS_IMS_UEAU                    ServiceName = "nhss-ims-ueau"
	SERVICENAME_NHSS_GBA_SDM                     ServiceName = "nhss-gba-sdm"
	SERVICENAME_NHSS_GBA_UEAU                    ServiceName = "nhss-gba-ueau"
	SERVICENAME_NSEPP_TELESCOPIC                 ServiceName = "nsepp-telescopic"
	SERVICENAME_NSORAF_SOR                       ServiceName = "nsoraf-sor"
	SERVICENAME_NSPAF_SECURED_PACKET             ServiceName = "nspaf-secured-packet"
	SERVICENAME_NUDSF_DR                         ServiceName = "nudsf-dr"
	SERVICENAME_NUDSF_TIMER                      ServiceName = "nudsf-timer"
	SERVICENAME_NNSSAAF_NSSAA                    ServiceName = "nnssaaf-nssaa"
	SERVICENAME_NNSSAAF_AIW                      ServiceName = "nnssaaf-aiw"
	SERVICENAME_NAANF_AKMA                       ServiceName = "naanf-akma"
	SERVICENAME_N5GDDNMF_DISCOVERY               ServiceName = "n5gddnmf-discovery"
	SERVICENAME_NMFAF_3DADATAMANAGEMENT          ServiceName = "nmfaf-3dadatamanagement"
	SERVICENAME_NMFAF_3CADATAMANAGEMENT          ServiceName = "nmfaf-3cadatamanagement"
	SERVICENAME_NEASDF_DNSCONTEXT                ServiceName = "neasdf-dnscontext"
	SERVICENAME_NEASDF_BASELINEDNSPATTERN        ServiceName = "neasdf-baselinednspattern"
	SERVICENAME_NDCCF_DATAMANAGEMENT             ServiceName = "ndccf-datamanagement"
	SERVICENAME_NDCCF_CONTEXTMANAGEMENT          ServiceName = "ndccf-contextmanagement"
	SERVICENAME_NNSACF_NSAC                      ServiceName = "nnsacf-nsac"
	SERVICENAME_NNSACF_SLICE_EE                  ServiceName = "nnsacf-slice-ee"
	SERVICENAME_NMBSMF_TMGI                      ServiceName = "nmbsmf-tmgi"
	SERVICENAME_NMBSMF_MBSSESSION                ServiceName = "nmbsmf-mbssession"
	SERVICENAME_NADRF_DATAMANAGEMENT             ServiceName = "nadrf-datamanagement"
	SERVICENAME_NBSP_GBA                         ServiceName = "nbsp-gba"
	SERVICENAME_NTSCTSF_TIME_SYNC                ServiceName = "ntsctsf-time-sync"
	SERVICENAME_NTSCTSF_QOS_TSCAI                ServiceName = "ntsctsf-qos-tscai"
	SERVICENAME_NTSCTSF_ASTI                     ServiceName = "ntsctsf-asti"
	SERVICENAME_NPKMF_KEYREQ                     ServiceName = "npkmf-keyreq"
	SERVICENAME_NPKMF_USERID                     ServiceName = "npkmf-userid"
	SERVICENAME_NPKMF_DISCOVERY                  ServiceName = "npkmf-discovery"
	SERVICENAME_NMNPF_NPSTATUS                   ServiceName = "nmnpf-npstatus"
	SERVICENAME_NIWMSC_SMSERVICE                 ServiceName = "niwmsc-smservice"
	SERVICENAME_NMBSF_MBS_US                     ServiceName = "nmbsf-mbs-us"
	SERVICENAME_NMBSF_MBS_UD_INGEST              ServiceName = "nmbsf-mbs-ud-ingest"
	SERVICENAME_NMBSTF_DISTSESSION               ServiceName = "nmbstf-distsession"
	SERVICENAME_NPANF_PROSEKEY                   ServiceName = "npanf-prosekey"
	SERVICENAME_NPANF_USERID                     ServiceName = "npanf-userid"
)
